# Generated by Django 5.0.1 on 2024-01-26 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ayaah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, max_length='255', null=True, upload_to='ayahs')),
                ('content', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
